name: flutter_background_service
description: A flutter plugin for executing dart code continously even application closed.
version: 0.2.8+1
repository: https://github.com/ekasetiawans/flutter_background_service

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_background_service_platform_interface: ^0.0.1
  flutter_background_service_android: ^0.0.1
  flutter_background_service_ios: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        default_package: flutter_background_service_android
      ios:
        default_package: flutter_background_service_ios
